name: 'tp-dcc-tools-rigging'
version: '1.0.0'
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Rigging tools package for tp-dcc framework'
displayName: 'tp-dcc-tools-rigging'
environment:
  PYTHONPATH:
    - '{self}'
    - '{self}/preferences'
  TPDCC_BASE_PATHS:
    - '{self}'
  TPDCC_TOOL_DEFINITION_MODULES:
    - '{self}/tp/tools/rig/jointtoolbox/tool.py'
    - '{self}/tp/tools/rig/noddle/tool.py'
    - '{self}/tp/tools/rig/skeletor/tool.py'
    - '{self}/tp/tools/rig/transferskinweights/tool.py'
  TPDCC_META_PATHS:
    - '{self}/tp/libs/rig/noddle/meta'
  # Noddle
  NODDLE_NAME_PRESET_PATH: "{self}/tp/libs/rig/noddle/naming"
  NODDLE_COMPONENTS_PATHS:
    - "{self}/tp/libs/rig/noddle/components"
  NODDLE_DESCRIPTORS_PATHS:
    - "{self}/tp/libs/rig/noddle/components"
commands:
  - '{self}/startup/rig.py'