name: 'tp-dcc-houdini'
version: '1.0.0'
required: True
author: 'Tomas Poveda'
authorEmail: 'tpovedatd@gmail.com'
description: 'Houdini package for tp-dcc Tools framework'
displayName: 'tpDcc Houdini'
environment:
  PYTHONPATH:
    - '{self}'
